### ISSUE TITLE
建议再加个功能-让用户可以删除自己点过的歌曲

### ISSUE THREAD

**Issue by Jack233XD** [kasuganosoras/SyncMusic#16]
我建议再加个功能，就是让用户可以删除自己点过的歌曲。因为有时候可能会点错歌，这样就可以删除自己点错的歌。

**Comment by Jack665Brown** [comment]
> 我建议再加个功能，就是让用户可以删除自己点过的歌曲。因为有时候可能会点错歌，这样就可以删除自己点错的歌。

**Comment by Jack233XD** [comment]
尴尬，发现原来有人说过这个歌曲撤回的，所以关闭issue了 草
