### ISSUE TITLE
已经获取到mp3链接，但下载失败

### ISSUE THREAD

**Issue by tmsdy** [kasuganosoras/SyncMusic#17]
Win7环境。
聊天发表情都ok了。
 
![TIM截图20191204173529](https://user-images.githubusercontent.com/12005139/70131288-fe0aba00-16bc-11ea-8c86-09714662f8db.jpg)

**Comment by tmsdy** [comment]
历尽千辛万苦才跳过了这个坑（win的路径全都要重新弄，并且swoole版本的php是用的Cygwin，路径要用/cygdrive/d/web/ 这样的格式）

另外swoole版本的php 执行shell_exec始终不成功，就换了个获取音乐长度的方案，用 getid3 (https://sourceforge.net/projects/getid3/)  替换了用python的方案。

然而还是没成功，错误如下
![TIM截图20191205122501](https://user-images.githubusercontent.com/12005139/70204317-0c0f1800-175b-11ea-8243-c1edc6da4b9c.jpg)

**Comment by kasuganosoras** [comment]
Windows 下可以使用 proc_open 替代 shell_exec 函数
```php
function win_exec($command) {
	$descriptorspec = array(
		0 => array("pipe", "r"),
		1 => array("pipe", "w"),
		2 => array("pipe", "r")
	);
	$process = proc_open($command, $descriptorspec, $pipes);
	$result = "";
	if (is_resource($process)) {
		while(!feof($pipes[1])) {
			$resule .= fread($pipes[0], 8192);
			$resule .= fread($pipes[1], 8192);
			$resule .= fread($pipes[2], 8192);
		}
		fclose($pipes[1]);
		fclose($pipes[0]);
		fclose($pipes[2]);
	}
	return $result;
}
```
另外可以尝试使用 WSL 子系统来运行

**Comment by tmsdy** [comment]
谢谢大佬   这个问题应该可以关了，我还有其它的问题，重新开一个
