### ISSUE TITLE
希望手机端和PC端还是能加个投票按钮

### ISSUE THREAD

**Issue by SoraKasvgano** [kasuganosoras/SyncMusic#2]
懒人表示还是按钮好用= =

然后下一首歌按ktv方式排序吧23333管理员调顺序

**Comment by kasuganosoras** [comment]
新的版本已经有按钮了，代码忘记传上来了（
可以先到 Demo 体验下，等会我改完几个 bug 就传新的代码上来

**Comment by SoraKasvgano** [comment]
emmm
歌名后面还可以再加一个，投票，然后当这首歌放完了之后，下一首歌自动放票数多的。（仅是意见，不知道和程序发展方向是否一致= =）
![捕获](https://user-images.githubusercontent.com/8521327/68493397-5fd73000-0287-11ea-9ada-c7050069e157.JPG)

**Comment by yueyericardo** [comment]
手机端，音乐加载不出来？

**Comment by kasuganosoras** [comment]
> 手机端，音乐加载不出来？

具体操作系统，浏览器类型？

**Comment by yueyericardo** [comment]
> > 手机端，音乐加载不出来？
> 
> 具体操作系统，浏览器类型？


ios, safari
[截图](https://user-images.githubusercontent.com/9999318/68611956-5c12fb80-0489-11ea-8db3-2b98508c8359.png)

**Comment by kasuganosoras** [comment]
iOS 下暂时无法播放，因为受限于 Safari 的特殊规定，网页无法主动播放音乐，而且我也没有 iOS 设备，没办法进行测试，抱歉。

**Comment by kasuganosoras** [comment]
这个投票选择下一首播放的音乐功能暂时不考虑增加了，因为要修改的地方太多，而且还要考虑一些问题，比如客户端断开连接后之前投过得票怎么算，有人可能会开一堆窗口刷票数然后故意放一些很难听的歌之类的。
如果没有其他问题的话这个 Issues 我就先关掉了，有问题可以回复重新开启。
