### ISSUE TITLE
非相同ip地址但是为同一个client

### ISSUE THREAD

**Issue by icebale** [kasuganosoras/SyncMusic#3]
直接分享链接给同事，他和我的client为同一个，我点击投票后他再点击投票显示已投过票，他发送信息的时候显示的昵称也是我的昵称，我们俩的IP地址只有最后一段不同

**Comment by kasuganosoras** [comment]
一般来说不太可能出现这个情况，有可能是因为某种原因在服务器那边识别到你们两个的 IP 是一样的，然后就当成同一个人了……

**Comment by icebale** [comment]
> 一般来说不太可能出现这个情况，有可能是因为某种原因在服务器那边识别到你们两个的 IP 是一样的，然后就当成同一个人了……

额，接的是交换机上的网线，这个有影响吗？让另一个同事试了下，打开链接也是一样的…… 我们本地做websocket测试的时候并没有这个问题，!!!∑(ﾟДﾟノ)ノ，

**Comment by kasuganosoras** [comment]
打开 ip138.com 看看 IP 地址是不是一样的，如果一样的话说明你们走的是同一个出口，所以识别到 IP 地址是一样的。。

**Comment by icebale** [comment]
> 打开 ip138.com 看看 IP 地址是不是一样的，如果一样的话说明你们走的是同一个出口，所以识别到 IP 地址是一样的。。

嗯嗯，是一样的
