### ISSUE TITLE
Akariin 

### ISSUE THREAD

**Issue by RaymondChang1204** [kasuganosoras/SyncMusic#31]
04-16 02:21:01 @10898.0]  WARNING swSocket_bind(:434): bind(0.0.0.0:81
ailed, Error: Address already in use[98]
PHP Fatal error:  Uncaught Swoole\Exception: failed to listen server port[0.
0:811], Error: Address already in use[98] in /www/wwwroot/www.zhanghongye132
z/SyncMusic.php:65
Stack trace:
#0 /www/wwwroot/www.zhanghongye1325.xyz/SyncMusic.php(65): Swoole\Server->__
truct()
#1 /www/wwwroot/www.zhanghongye1325.xyz/server.php(82): SyncMusic->init()
#2 {main}
  thrown in /www/wwwroot/www.zhanghongye1325.xyz/SyncMusic.php on line 65

Fatal error: Uncaught Swoole\Exception: failed to listen server port[0.0.0.0
], Error: Address already in use[98] in /www/wwwroot/www.zhanghongye1325.xyz
cMusic.php:65
Stack trace:
#0 /www/wwwroot/www.zhanghongye1325.xyz/SyncMusic.php(65): Swoole\Server->__
truct()
#1 /www/wwwroot/www.zhanghongye1325.xyz/server.php(82): SyncMusic->init()
#2 {main}
  thrown in /www/wwwroot/www.zhanghongye1325.xyz/SyncMusic.php on line 65
启动时显示这个 不知道怎么一回事

**Comment by kasuganosoras** [comment]
服务器已经被端口占用，换一个就行了
