### ISSUE TITLE
MKOnlineMusicPlayer 返回MP3格式

### ISSUE THREAD

**Issue by HolgerHuo** [kasuganosoras/SyncMusic#40]
您好~想请问一下，按照官方教程搭建的MKOnlineMusicPlayer返回的是flac格式，SyncMusic无法读取长度导致播放失败。但您搭建的后端返回的就是mp3，想请问一下您的是做了什么修改吗？

**Comment by HolgerHuo** [comment]
原因是我填入了自己网易云的cookie……
如果使用默认的就不会有问题了……

**Comment by kasuganosoras** [comment]
你氪了会员，它自然会返回无损的格式。。
用个普通账号的 Cookie 就没事了

**Comment by HolgerHuo** [comment]
> 你氪了会员，它自然会返回无损的格式。。
> 用个普通账号的 Cookie 就没事了

我尝试了一下 还真不太是
原因是因为我上传了云盘😂
所以用自己cookie回调的都是自己云盘里的歌（因为那个meting的api会默认320k码率，就算是会员回调的也应该是320kpbs的mp3）
不过成功的利用这个机制恢复了很多首周杰伦的歌
