### ISSUE TITLE
昵称缺少关键字、敏感字过滤，昵称长度不知道有没有限制

### ISSUE THREAD

**Issue by Xavier9896** [kasuganosoras/SyncMusic#5]
如题 👆
昵称缺少关键字、敏感字过滤，昵称长度不知道有没有限制

**Comment by kasuganosoras** [comment]
目前已支持敏感词限制，通过增加指定关键字黑名单即可，支持屏蔽歌名、歌手、专辑名以及聊天昵称，聊天内容暂未限制，可以通过自行修改代码实现。
