### ISSUE TITLE
音量自动调整

### ISSUE THREAD

**Issue by Taskeren** [kasuganosoras/SyncMusic#6]
可以把音量放cookies里，每次进入自动调整到原来的大小，不然每次进来都是一次对耳朵的迫害。

**Comment by kasuganosoras** [comment]
在新的更新中已支持：[7103e4c
](https://github.com/kasuganosoras/SyncMusic/commit/7103e4c2ddf2039415f422864751e3c3f1293a65)

使用了 localStorage 进行储存。

**Comment by Taskeren** [comment]
新BUG。
进入页面后音量没有问题，但是点击`音量控制`后又直接跳到最大值了。
