### ISSUE TITLE
运行php server.php出错

### ISSUE THREAD

**Issue by w2r** [kasuganosoras/SyncMusic#7]
错误提示：
WARNING swShareMemory_mmap_create: mmap(10318800632) failed. Error: Cannot allocate memory[12]
PHP Fatal error:  Swoole\Table::create(): unable to allocate memory. in /root/SyncMusic/SyncMusic.php on line 81

Fatal error: Swoole\Table::create(): unable to allocate memory. in /root/SyncMusic/SyncMusic.php on line 81
这个错误解决了。server已经后台运行了，服务器后台产生了一大堆 php server.php进程，可是打开网页一直无法连接服务器，

**Comment by Xavier9896** [comment]
bug+1，我也是这样，改了 php 配置后能跑起来，但是连不上

**Comment by w2r** [comment]
> bug+1，我也是这样，改了 php 配置后能跑起来，但是连不上

感觉像是swoole的问题，new Swoole\Table(65535);，655335太大了，我百度好久，好像要求是8的倍数，我改成8000，然后php可以后台运行，产生一堆server.php进程，应该是后端没配置好，可惜不会php，不会查bug，只能留下无助的眼泪

**Comment by kasuganosoras** [comment]
确实是错误，65535 其实是行数，行数过大 PHP 无法申请到足够的内存空间于是就报了上面的错误。
解决办法就是改成小一点的数字，比如 1024、2048
修复后的代码已经更新，请见 SyncMusic.php
